### ISSUE TITLE
SSR authentication through cookies

### ISSUE THREAD

**Issue by Blackening999** [damassi/react-relay-network-modern-ssr-todomvc#1]
Hello,

it's an amazing example you have created here which answers most questions. However, I was struggling to set a cookie from mutation.

```js
onst GraphQLAddTodoMutation = mutationWithClientMutationId({
  name: 'AddTodo',
  inputFields: {
    text: { type: new GraphQLNonNull(GraphQLString) },
  },
  outputFields: {
    viewer: {
      type: GraphQLUser,
      resolve: getViewer,
    },
    todoEdge: {
      type: GraphQLTodoEdge,
      resolve: ({ todoId }, _, { res }) => {
        const todo = getTodo(todoId);

        var randomNumber=Math.random().toString();
        randomNumber=randomNumber.substring(2,randomNumber.length);
        res.cookie('cookieName',randomNumber, { maxAge: 900000, httpOnly: true });

        return {
          cursor: cursorForObjectInConnection(getTodos(), todo),
          node: todo,
        };
      },
    },
  },
  mutateAndGetPayload: ({ text }) => {
    const todoId = addTodo(text);
    return { todoId };
  },
});
```

As you can see, I have exposed context to resolve method and tried to set a cookies from it
**res.cookie('cookieName',randomNumber, { maxAge: 900000, httpOnly: true });**

NOTE: I have added and connected cookieParser in the server before

When I add cookie directly from middleware if works as it should, but when I attempt to do that through mutation - the cookies are ignored. 
When I used standard relayEnvironment it worked well

Can you help please? I guess it's a problem somewhere in an isomorphic-fetch which doesn't dispatch response to a browser properly

P.S. I also use Koa in my real project - but this doesn't matter as it fails there as well

Thank you!

**Comment by Blackening999** [comment]
Damn... ) In relayEnvironment instead of providing custom middleware and setting credentials = 'true' on a fetchOptions I should have used urlMiddleware hash instead

**Comment by damassi** [comment]
@Blackening999 - did `urlMiddleware` solve your problem? It exposes the underlying `fetch` API so that you can get / set whatever you need.

**Comment by Blackening999** [comment]
@damassi If you check this example: https://github.com/relay-tools/react-relay-network-modern#example-of-injecting-networklayer-with-middlewares-on-the-client-side

You will see that:
```js
 // example of the custom inline middleware
    next => async req => {
      req.fetchOpts.method = 'GET'; // change default POST request method to GET
      req.fetchOpts.headers['X-Request-ID'] = uuid.v4(); // add `X-Request-ID` to request headers
      req.fetchOpts.credentials = 'same-origin'; // <<<<<<<<< allow to send cookies (sending credentials to same domains)
      // req.fetchOpts.credentials = 'include'; // allow to send cookies for CORS (sending credentials to other domains)

      console.log('RelayRequest', req);

      const res = await next(req);
      console.log('RelayResponse', res);

      return res;
    },
```

It is a **misleading** example which killed for me around 4hrs debugging the whole chain of libraries including that non-sense generator pattern with numbers as states which is hard to read to only realise that this middleware setting is completely ignored

When I put it here - it just works 
```js  
    urlMiddleware({
      credentials: 'same-origin',
      url: 'http://localhost:8080/graphql',
    }),
```

**Comment by damassi** [comment]
@Blackening999 - nice, glad you found a fix. When I get some time I'd like to update the docs over there so they're a little more clear, but like everything in the Relay modern community we devs are kinda left to figure things out while the patterns materialize / settle.
